version: '2'
services:
  paymentscatalogservice-app:
    image: paymentscatalogservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://paymentscatalogservice-postgresql:5432/PaymentsCatalogService
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  paymentscatalogservice-postgresql:
    extends:
      file: postgresql.yml
      service: paymentscatalogservice-postgresql
